feat(common): init
dlioon/assessment pull request #1
Opened 2023-01-04 15:29 UTC by dlioon

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/main.ts
> +  });
`app.useGlobalPipes(new ValidationPipe());`

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/numbers/services/number.service.ts
> +export class NumberService {
сінгл респонсібіліті і опен клоуз страждають. По факту сервіс в тебе для внутрішнього користування. Якщо ти хочеш під нуль проксувати то ок, але я б зробив не так, я б залишив цей сервіс внутрішнім і не експортував би його, а створив би фасад в якому були б обгортки, в яких будуть просто методи з юзерфрендлі іменами, та простими параметрами, як в тебе методд селл намбер. І експортував би цей фасад в модулі. По факту в тебе створиться API цього мікросервісу, з зовнішнім інтерфейсом, який скоріше не зміниться ніколи. А от якщо в тебе зміниться джерело, то ти просто перепишеш ядро і фасад, а сам інтерфейс на виході залишиться сталим, що є бест пректісіс при розробці мікросервісів. Щоб потім не чипати сервіси, які його використовують

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/payments/controllers/payment.controller.ts
> +  @Post('/webhook/stripe')
plural webhooks

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/payments/controllers/payment.controller.ts
> +  @Post('/webhook/stripe')
customize on stripe side

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/payments/entities/payment.entity.ts
> +import { PaymentItem } from './payment-item.entity';
I would prefer ...graphql.entity naming

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/payments/payment.module.ts
> +            port: config.get<number>('MODULE_PAYMENTS_PORT'),
create separated config and an appropriate MictoserviceConfig type which is waiting for host and port params

2023-02-13 06:01 UTC, Dimona commented on backend/applications/gateway/src/payments/services/payment.service.ts
> +  async send(
put into lib and correctly name it. CommandModule or make an Abstraction as CommandService

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/database/config/database.config.ts
> +  entities: [path.resolve(__dirname, '../../**/*.entity{.ts,.js}')],
check if it's necessary to write (migrations and entities) in the latest version

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/numbers/controllers/number.controller.ts
> +    return this.dataSource.transaction((manager) => {
Put into service

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/main.ts
> +  await app.listen();
add swagger server start

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/numbers/dtos/sell-number.dto.ts
> +  @IsNotEmpty()
Add

@IsArray()
@ArrayMinSize(1)

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/numbers/entities/number-user.entity.ts
> +  @Column({ type: 'varchar', nullable: false })
length?

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/numbers/entities/number-user.entity.ts
> +  @Column({ type: 'varchar', nullable: false })
length?

2023-02-13 06:01 UTC, Dimona commented on backend/applications/numbers/src/numbers/services/number.service.ts
> +    const userNumbers: Partial<NumberUser>[] = params.numberIds.reduce(
map

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/main.ts
> +  app.useGlobalFilters(new RpcExceptionFilter());
pipes

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/payment/controllers/payment.controller.ts
> +  }
put into another controller

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/payment/services/payment.service.ts
> +  async processStripeWebhook(data: StripeWebhookDto): Promise<Payment | null> {
rename to concrete action

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/payment/services/payment.service.ts
> +          // TODO: handle error
do it

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      throw new StripeException({
тобто всі ексепшени, що виплюне страйп ти суєш в бед ріквест. Так нізя, код також треба проксувати

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      console.log(error);
використовуй Logger

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      throw new StripeException({
в лог теж треба щось виводити

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/stripe/exceptions/stripe.exception.ts
> +    super(params, HttpStatus.BAD_REQUEST);
дивись нижче

2023-02-13 06:01 UTC, Dimona commented on backend/applications/payments/src/stripe/stripe.module.ts
> +          apiVersion: '2022-11-15',
винеси в енв і конфіг

2023-02-13 06:01 UTC, Dimona commented on backend/applications/users/src/auth/dtos/register.dto.ts
> +  @MinLength(8)
хочу щоб ти кастомний декоратор написав, який буде валідувати мінімальну складність паролю. Принаймні 1 намбер, 1 стрінг, 1 спецсимвол

2023-02-13 06:01 UTC, Dimona commented on backend/applications/users/src/firebase/exceptions/firebase.exception.ts
> +    super(params, HttpStatus.BAD_REQUEST);
та ж проблема, що в страйпі

2023-02-13 06:01 UTC, Dimona commented on backend/applications/users/src/firebase/types/error.type.ts
> +export type ErrorType = {
бачу ти захотів трохи універсилізувати. Цей тайп піде в ліби, можеш створити лібу контракти, де будуть типи, які використовуються в різних сервісах

2023-02-13 06:01 UTC, Dimona commented on backend/applications/users/src/main.ts
> +      port: process.env.PORT || 6001,
дефолт порт в константи

2023-02-13 06:01 UTC, Dimona commented on backend/applications/users/src/utils/exception-filters/rpc.filter.ts
> +export class RpcExceptionFilter implements ExceptionFilter {
повторюється в кожному сервісі, ліба біба

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/MainLayout/index.tsx
> +}
я так і не зрозумів, Лойко теж так пише. Я так зрозумів писати FC<Props> вже не модно?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Loader/index.tsx
> +    <></>
а це обов'язково? чи можна було просто
isLoading && (...)

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/components/ModalTitle.tsx
> +  onClose?: () => void;
type

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +  readonly onClose?: (...rest: any) => void;
типи якісь дивні попрацюй над ними

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +}: Props): [(props?: any) => void, () => void] => {
ох тут ми клали на тайпскрипт, попрацюй

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +  const [showProps, setShowProps] = useState<{ [key: string]: any }>({});
Record<string, any>

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +        if (closeOnSubmit) hideModal();
іф в один ряядок, переробити на блочну структуру

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +      setIsLoading(false);
засунь в файналі

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +    const handleClose = (...rest: any[]) => {
тип

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +    const handleSubmit = async (...rest: any) => {
юз колбек

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +    const handleClose = (...rest: any[]) => {
юз колбек

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/auth/hooks/api.ts
> +export const useUserMeQuery = (options?: QueryHookOptions): QueryResult<User> =>
дивне ім'я

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/auth/providers/index.tsx
> +      setIsReady(true);
ретурна немає, перенести в файналі

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/auth/providers/index.tsx
> +      setIsReady(true);
перенести в файналі

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/components/CartModal/index.tsx
> +  cart: any;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/components/CartModal/index.tsx
> +  onClose: () => void;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/context/index.ts
> +  addToCart: (product: any) => {},
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly clearCart: () => void;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly addToCart: (product: any) => void;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly cart: any;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +    itemAdded(state: any, action: any) {
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +        (item: any) => item.id === product.id,
? деструктуризація

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +    itemRemoved(state: any, action: PayloadAction<number>) {
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +        (item: any) => item.id === action.payload,
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/Payment.tsx
> +  items: any;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/Payment.tsx
> +  onClose: () => void;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +  items: any;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +  updateSecret: () => Promise<void>;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +          return_url: 'http://localhost:3000',
конфіг

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +      }
багато блоків, перенеси в файналі, зроби короткий іф з ретьорном, та зроби структуру більш плоскою

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/payments/hooks/api.ts
> +`;
страшне, виглядає погано, але шо поробиш

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/phones/components/BuyPhoneModal/index.tsx
> +  onClose: () => void;
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/phones/components/PhoneNumbersTable.tsx
> +    (row: any) => async () => {
?

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/app/components/query/configs/apollo.ts
> +  uri: process.env.REACT_APP_BACKEND_URL || 'http://localhost:3005/graphql',
default link to constant

2023-02-13 06:01 UTC, Dimona commented on frontend/src/src/reportWebVitals.ts
> +export default reportWebVitals;
а шо це розкажеш?

2023-02-24 19:52 UTC, dlioon commented on backend/applications/numbers/src/main.ts
> +  });
+

2023-02-24 19:53 UTC, dlioon commented on backend/applications/gateway/src/payments/controllers/payment.controller.ts
> +  @Post('/webhook/stripe')
done

2023-02-24 19:57 UTC, dlioon commented on backend/applications/gateway/src/payments/entities/payment.entity.ts
> +import { PaymentItem } from './payment-item.entity';
done

2023-02-24 20:05 UTC, dlioon commented on backend/applications/gateway/src/payments/payment.module.ts
> +            port: config.get<number>('MODULE_PAYMENTS_PORT'),
done

2023-02-24 20:15 UTC, dlioon commented on backend/applications/numbers/src/database/config/database.config.ts
> +  entities: [path.resolve(__dirname, '../../**/*.entity{.ts,.js}')],
autoLoadEntities: true 
With that option specified, every entity registered through the forFeature() method will be automatically added to the entities array of the configuration object.

WARNING
Note that entities that aren't registered through the forFeature() method, but are only referenced from the entity (via a relationship), won't be included by way of the autoLoadEntities setting


без migrations не працюють міграції

2023-02-27 18:04 UTC, dlioon commented on backend/applications/numbers/src/numbers/controllers/number.controller.ts
> +    return this.dataSource.transaction((manager) => {
В документації nest-transact в прикладах написано що треба саме так використовувати
https://www.npmjs.com/package/nest-transact

2023-02-27 18:08 UTC, dlioon commented on backend/applications/numbers/src/main.ts
> +  await app.listen();
done

2023-02-27 18:13 UTC, dlioon commented on backend/applications/numbers/src/numbers/dtos/sell-number.dto.ts
> +  @IsNotEmpty()
done

2023-02-27 18:13 UTC, dlioon commented on backend/applications/numbers/src/numbers/entities/number-user.entity.ts
> +  @Column({ type: 'varchar', nullable: false })
done

2023-02-27 18:13 UTC, dlioon commented on backend/applications/numbers/src/numbers/entities/number-user.entity.ts
> +  @Column({ type: 'varchar', nullable: false })
done

2023-02-27 18:14 UTC, dlioon commented on backend/applications/numbers/src/numbers/services/number.service.ts
> +    const userNumbers: Partial<NumberUser>[] = params.numberIds.reduce(
done

2023-02-27 18:18 UTC, dlioon commented on backend/applications/payments/src/main.ts
> +  app.useGlobalFilters(new RpcExceptionFilter());
done

2023-02-27 18:25 UTC, dlioon commented on backend/applications/payments/src/payment/controllers/payment.controller.ts
> +  }
done

2023-02-27 18:29 UTC, dlioon commented on backend/applications/payments/src/payment/services/payment.service.ts
> +  async processStripeWebhook(data: StripeWebhookDto): Promise<Payment | null> {
Наприклад? Ми ж обробляємо вебхук від страйпу, наче правильне ім'я

2023-02-27 18:32 UTC, dlioon commented on backend/applications/payments/src/payment/services/payment.service.ts
> +          // TODO: handle error
done

2023-02-27 18:35 UTC, dlioon commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      throw new StripeException({
done

2023-02-27 18:38 UTC, dlioon commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      console.log(error);
done

2023-02-27 18:40 UTC, dlioon commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +      throw new StripeException({
done

2023-02-27 18:40 UTC, dlioon commented on backend/applications/payments/src/stripe/exceptions/stripe.exception.ts
> +    super(params, HttpStatus.BAD_REQUEST);
done

2023-02-27 18:41 UTC, dlioon commented on backend/applications/payments/src/stripe/stripe.module.ts
> +          apiVersion: '2022-11-15',
done

2023-02-27 18:44 UTC, dlioon commented on backend/applications/users/src/firebase/exceptions/firebase.exception.ts
> +    super(params, HttpStatus.BAD_REQUEST);
done

2023-02-27 18:46 UTC, dlioon commented on backend/applications/users/src/main.ts
> +      port: process.env.PORT || 6001,
done

2023-02-27 18:48 UTC, dlioon commented on frontend/src/src/app/components/MainLayout/index.tsx
> +}
судячи з https://github.com/facebook/create-react-app/pull/8177 , то вже не модно

2023-02-27 18:51 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Loader/index.tsx
> +    <></>
зробив трошки по іншому, обернув все в <></> інакше була помилка Loader' cannot be used as a JSX component.   Its return type 'false | Element' is not a valid JSX element.

2023-02-27 18:54 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/components/ModalTitle.tsx
> +  onClose?: () => void;
а що з ним не так?

2023-02-27 18:55 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +  readonly onClose?: (...rest: any) => void;
це брав з інших проектів, там такі ж типи, замінив просто на params: any

2023-02-27 19:06 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +  const [showProps, setShowProps] = useState<{ [key: string]: any }>({});
done

2023-02-27 19:06 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +        if (closeOnSubmit) hideModal();
done

2023-02-27 19:06 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +      setIsLoading(false);
done

2023-02-27 19:08 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +    const handleClose = (...rest: any[]) => {
done

2023-02-27 19:09 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +    const handleSubmit = async (...rest: any) => {
done

2023-02-27 19:12 UTC, dlioon commented on frontend/src/src/app/components/auth/hooks/api.ts
> +export const useUserMeQuery = (options?: QueryHookOptions): QueryResult<User> =>
done

2023-02-27 19:12 UTC, dlioon commented on frontend/src/src/app/components/auth/providers/index.tsx
> +      setIsReady(true);
done

2023-02-27 19:13 UTC, dlioon commented on frontend/src/src/app/components/auth/providers/index.tsx
> +      setIsReady(true);
done

2023-02-27 19:19 UTC, dlioon commented on frontend/src/src/app/components/cart/components/CartModal/index.tsx
> +  cart: any;
done

2023-02-27 19:20 UTC, dlioon commented on frontend/src/src/app/components/cart/context/index.ts
> +  addToCart: (product: any) => {},
done

2023-02-27 19:20 UTC, dlioon commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly cart: any;
done

2023-02-27 19:20 UTC, dlioon commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly addToCart: (product: any) => void;
done

2023-02-27 19:30 UTC, dlioon commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +    itemAdded(state: any, action: any) {
done

2023-02-27 19:31 UTC, dlioon commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +        (item: any) => item.id === product.id,
done

2023-02-27 19:31 UTC, dlioon commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +    itemRemoved(state: any, action: PayloadAction<number>) {
done

2023-02-27 19:31 UTC, dlioon commented on frontend/src/src/app/components/cart/slices/cartSlice.ts
> +        (item: any) => item.id === action.payload,
done

2023-02-27 19:33 UTC, dlioon commented on frontend/src/src/app/components/payments/components/Payment.tsx
> +  items: any;
done

2023-02-27 19:33 UTC, dlioon commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +  items: any;
done

2023-02-27 19:35 UTC, dlioon commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +          return_url: 'http://localhost:3000',
done

2023-02-27 19:40 UTC, dlioon commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +      }
done

2023-02-27 19:40 UTC, dlioon commented on frontend/src/src/app/components/payments/hooks/api.ts
> +`;
+

2023-02-27 19:42 UTC, dlioon commented on frontend/src/src/app/components/phones/components/PhoneNumbersTable.tsx
> +    (row: any) => async () => {
done

2023-02-27 19:43 UTC, dlioon commented on frontend/src/src/app/components/query/configs/apollo.ts
> +  uri: process.env.REACT_APP_BACKEND_URL || 'http://localhost:3005/graphql',
done

2023-03-02 18:42 UTC, dlioon commented on frontend/src/src/reportWebVitals.ts
> +export default reportWebVitals;
це бібліотека що допомагає виміряти перфоманс, але я ніколи нею не користувався, тому в деталях не розкажу

2023-03-02 19:06 UTC, dlioon commented on backend/applications/users/src/auth/dtos/register.dto.ts
> +  @MinLength(8)
done

2023-03-02 19:15 UTC, dlioon commented on backend/applications/users/src/utils/exception-filters/rpc.filter.ts
> +export class RpcExceptionFilter implements ExceptionFilter {
done

2023-03-02 19:18 UTC, dlioon commented on backend/applications/users/src/firebase/types/error.type.ts
> +export type ErrorType = {
done

2023-03-02 19:21 UTC, dlioon commented on backend/applications/numbers/src/main.ts
> +  await app.listen();
а свагер неможливо запустити в мікросервісі, він не хоче приймати app, який створений як NestFactory.createMicroservice

https://stackoverflow.com/questions/65983926/swagger-like-to-nestjs-microservices

2023-03-02 19:41 UTC, dlioon commented on backend/applications/gateway/src/payments/services/payment.service.ts
> +  async send(
done

2023-03-02 19:43 UTC, dlioon commented on backend/applications/gateway/src/numbers/services/number.service.ts
> +export class NumberService {
я просто виніс send метод в лібу та залишив проксування в цьому сервісі

2023-03-21 18:28 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/components/ModalTitle.tsx
> +  onClose?: () => void;
done

2023-03-21 18:30 UTC, dlioon commented on frontend/src/src/app/components/cart/components/CartModal/index.tsx
> +  onClose: () => void;
done

2023-03-21 18:32 UTC, dlioon commented on frontend/src/src/app/components/cart/context/index.ts
> +  readonly clearCart: () => void;
тут функція не потребує ніяких параметрів, викликається тільки коли payment success clearCart();

2023-03-21 18:32 UTC, dlioon commented on frontend/src/src/app/components/payments/components/Payment.tsx
> +  onClose: () => void;
done

2023-03-21 18:34 UTC, dlioon commented on frontend/src/src/app/components/payments/components/PaymentForm.tsx
> +  updateSecret: () => Promise<void>;
тут функція не потребує ніяких параметрів, викликається аби оновити client_secret від страйпу

2023-03-21 18:34 UTC, dlioon commented on frontend/src/src/app/components/phones/components/BuyPhoneModal/index.tsx
> +  onClose: () => void;
done

2023-03-21 18:50 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +}: Props): [(props?: any) => void, () => void] => {
done

2023-03-21 18:50 UTC, dlioon commented on frontend/src/src/app/components/Theme/components/Modal/hooks/useModal.tsx
> +  readonly onClose?: (...rest: any) => void;
done

2023-03-26 06:33 UTC, Dimona requested changes

2023-03-26 06:33 UTC, Dimona commented on backend/applications/numbers/src/main.ts
> +  await app.listen();
тоді апідоки кожного мікросервісу фігач в окремий файл openapi.yml

```typescript
import { default as fs } from 'fs';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { default as yaml } from 'js-yaml';
import { INestApplication } from '@nestjs/common';

export type GenerateSwaggerDocumentationOptions = {
  app: INestApplication; // Application
  title: string; // Swagger title
  description?: string; // Swagger description
  version: string; // Project version
  file?: string; // File path to swagger yaml file
};

export const DEFAULT_FILE_PATH = './openapi.yml';

export const generateSwaggerDocumentation = ({
  app,
  file = DEFAULT_FILE_PATH,
  title,
  version,
  description,
}: GenerateSwaggerDocumentationOptions): void => {
  const swaggerOptions = new DocumentBuilder().setTitle(title).setDescription(description).setVersion(version).build();
  const document = SwaggerModule.createDocument(app, swaggerOptions);

  // Save swagger to openapi doc
  fs.writeFileSync(file, yaml.dump(document));
};

```

2023-03-26 06:33 UTC, Dimona commented on backend/applications/numbers/src/numbers/controllers/number.controller.ts
> +    return this.dataSource.transaction((manager) => {
я подивися, не бачив цієї реалізації. Дуже сподобалася. А ще сподобалося, як екстендяться репозиторії без декораторів. Тому для мене прям було щось нове.

2023-03-26 06:33 UTC, Dimona commented on backend/applications/payments/src/stripe/controllers/stripe.controller.ts
> +  }
ентер

2023-03-26 06:33 UTC, Dimona commented on backend/applications/payments/src/payment/services/payment.service.ts
> +  async processStripeWebhook(data: StripeWebhookDto): Promise<Payment | null> {
я подивився як у мене, так у мене також на всі івенти стріляє один і той самий вебхук на один мій ендпоінт. Хай буде

2023-03-26 06:33 UTC, Dimona commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +    const event: Stripe.Event = await this.constructEvent(data);
йому не місце в сервісі, це ще на етапі прийому ріквесту повинно статися, тому винести констрактІвент в інтерсептор і додати його прям в ріквест, а в контроллері його витягнути і передавати сюди вже як параметр

2023-03-26 06:33 UTC, Dimona commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +  }
оцей метод це зло, тут попахує патерном фекторі і на кожен івент треба викликати свій обробник, або як не хочеш плодити класи, можеш хоча б на кожен тип свій обробник, тоді буде ще конфіг який замапить івент тайпи на методи

2023-03-26 06:33 UTC, Dimona commented on frontend/src/src/app/components/MainLayout/index.tsx
> +}
я зрозумів

2023-03-27 18:45 UTC, dlioon commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +  }
done

2023-03-27 18:45 UTC, dlioon commented on backend/applications/payments/src/stripe/services/stripe.service.ts
> +    const event: Stripe.Event = await this.constructEvent(data);
done

2023-03-27 18:45 UTC, dlioon commented on backend/applications/payments/src/stripe/controllers/stripe.controller.ts
> +  }
done

2023-03-27 18:56 UTC, dlioon commented
Оцей метод що ти пропонуєш generateSwaggerDocumentation теж не підходить, бо SwaggerModule.createDocument приймає тільки INestApplication, а в мене вони всі INestMicroservice, чи може я щось не правильно розумію?

2023-05-10 18:17 UTC, merged